spec/helpers/application_helper_spec.rb
=> improve application controller rspec file.

Rakefile, config.ru, config/application.rb, config/environment.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/initializers/secret_token.rb, config/initializers/session_store.rb, config/routes.rb
=> Renames the project

.gitignore, .travis.yml, Gemfile, bin/setup
Related old issue: https://github.com/call4paperz/call4paperz/pull/110
=> Sets default ruby version used in project to 2.2.3

README.md
this project scan all gems looking for security vulnerabilities
=> [ci-skip] add hakiri badge

README.md, app/views/layouts/_footer.html.erb
=> update current Maintainers

doc/README_FOR_APP
This PR removes unused `/doc` folder.
=> Remove /doc folder

bin/setup, db/seeds.rb
Just create seed data, useful for project startup.
closes #152
=> Create seed data

app/controllers/comments_controller.rb, app/views/comments/new.html.erb, config/routes.rb
Call4paperz only allows users to create comments, so this PR cleans up `comments_controller.rb`
=> Clean up comments_controller.rb

app/controllers/home_controller.rb, app/views/home/index.html.erb, spec/controllers/home_controller_spec.rb
Bug fix: Show only active events total on home page.
=> Show only total active events on home page

app/controllers/comments_controller.rb, app/controllers/events_controller.rb, app/controllers/proposals_controller.rb
Looks like the app is not responding to xml
closes #159
=> Remove xml responses in controllers

app/models/vote.rb
Remove useless private modifier in vote.rb reported by code climate: 
https://codeclimate.com/github/call4paperz/call4paperz/app/models/vote.rb
=> Remove useless private modifier in vote.rb

app/controllers/proposals_controller.rb, config/locales/en.yml
removing code duplication
https://codeclimate.com/github/call4paperz/call4paperz/compare/proposal-enhancement
=> proposal enhancement. fixing codeclimate error

Dockerfile, bin/setup, config/database.yml.sample, docker-compose.override.yml.sample
Changes database.yml.sample, since the setup script would only replace the user with the system's user inside the env var `USER`, making the database.yml.sample already check for a DB_USER and if don't find it, use USER.
Also, edit Dockerfile to install bundle files inside a path that's already in gitignore
=> Edit postgres user

.gitignore, README.md
Update README.md to explain better the steps needed to run the application using Docker in development and add the tested Docker versions.
related to #189
=> Update readme for docker

Gemfile, Gemfile.lock
`addressable` gem is not being used.
=> Remove addressable gem

script/merge_user, script/rails
Let's get rid of unused scripts.
=> Remove unused scripts

app/assets/stylesheets/_constants.scss, app/assets/stylesheets/style.css.scss, app/assets/stylesheets/widgets.css.scss
Let's change everything to en.
=> Rename css variables

Gemfile.lock
See https://hakiri.io/github/call4paperz/call4paperz/master/918b7dc164c0f34db507590ad09d17389e38d6d9/warnings?name=Information+Disclosure
=> bundle update. fixing sprockets CVE-2018-3760

README.md
Add new maintainer and removing old ones.
Old contributors/ maintainers are gonna to be found in the contributors section. (it's actually an old suggestion)
=> Update Maintainer section

README.md
See https://docs.gitlab.com/ee/user/project/import/gemnasium.html
=> Removing Gemnasium badge

app/assets/javascripts/call4paperz.js, app/views/home/index.html.erb
Current Twitter integration is broken:
Endpoint: http://call4paperz.com/twitter/last.json
=> Fix twitter integration

app/views/registrations/new.html.erb
There is a javascript without script tag on Sign up page.
That's why the code appear at footer.
Issue: https://github.com/call4paperz/call4paperz/issues/330
=> fixed sign up page bug

app/views/layouts/application.html.erb
Fixed google adsense aligned on footer and added a conditional to load google adsense javascript only in production.
=> Fixed google adsense lined in footer
